blank_issues_enabled: false
contact_links:
  - name: Q&A
    url: https://github.com/ChenXu233/YaoXiang/discussions
    about: For general questions and usage discussions, please use Discussions first
